### PR TITLE
Fix #5 by removing jackson from core dependencies

### LINKED ISSUE #5: Remove unneeded dependencies
We do not need to depend on the entirety of GradleRIO. (we don't need the task `gradle deploy` for example)

### PR DESCRIPTION
**Pull request by ritikmishra**

### CODE REVIEW

**Comment by andrewgazelka** [comment]
> > I think serializers/deserializers should be registered per implementation, not interface...
> 
> Jackson will struggle at best to figure out which deserializer, if it exists, to use to get JSON data back into `List<IPathSegment>` when deserializing `Path`

Have you tested this? So if you have, let's say `A implements IPathSegment`, `B extends A`, and you register serializers for both `A.class` and `B.class`, Jackson will get mixed up?

**Comment by ritikmishra** [comment]
brb testing

**Comment by ritikmishra** [comment]
So it turns out that deserialization is the real problem. When deserializing an `List<IPathSegment>` into Java, Jackson does not know what implementation of `IPathSegment` to instantiate. One solution is to use a custom deserializer (another is to stick a Jackson annotation in the `IPathSegment` interface which we want to avoid). The custom deserializer can look at the JSON and decide what kind of class to instantiate. Normally, class information is not in the JSON, but with a custom _serializer_, we can insert the class name in the JSON making deserialization easy and possible.

**Comment by andrewgazelka** [comment]
let's resolve merge conflicts and merge

**Pull request merged**
